platform: linux

image_resource:
  type: registry-image
  source:
    repository: gcr.io/compute-image-tools/daisy

inputs:
- name: compute-image-tools

run:
  path: /daisy
  args:
  - -project=gce-image-builder
  - -zone=us-central1-c
  - -var:gcs_url=((gcs_url))
  - -compute_endpoint_override=https://www.googleapis.com/compute/beta/projects/
  - ./compute-image-tools/daisy_workflows/build-publish/((wf))
